"""
Visualizations Page - Display healthcare data visualizations.
"""
import streamlit as st
from io import BytesIO
from PIL import Image


def fetch_visualization(api_client, filename: str):
    """
    Fetch visualization image from API.
    
    Args:
        api_client: API client instance
        filename: Name of the visualization file
        
    Returns:
        PIL Image object or None if fetch failed
    """
    try:
        image_bytes = api_client.get_visualization(filename)
        return Image.open(BytesIO(image_bytes))
    except Exception as e:
        st.error(f"Failed to load {filename}: {str(e)}")
        return None


def render_visualization_card(title: str, description: str, image, col):
    """
    Render a visualization card with title, description, and image.
    
    Args:
        title: Card title
        description: Card description
        image: PIL Image object
        col: Streamlit column to render in
    """
    with col:
        st.markdown(
            f"""
            <div style='
                background-color: #FFFFFF;
                border: 1px solid #E5E7EB;
                border-radius: 16px;
                padding: 24px;
                margin-bottom: 24px;
                box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.02);
            '>
                <h3 style='
                    font-size: 20px;
                    font-weight: 800;
                    color: #000000;
                    margin-bottom: 8px;
                    letter-spacing: -0.02em;
                '>{title}</h3>
                <p style='
                    font-size: 14px;
                    color: #6B7280;
                    margin-bottom: 0;
                '>{description}</p>
            </div>
            """,
            unsafe_allow_html=True
        )
        
        if image:
            st.image(image, use_container_width=True)
        else:
            st.warning("Visualization not available")


def render():
    """Main render function for Visualizations page."""
    st.title("Visualizations")
    st.markdown(
        "Visual representations of healthcare metrics and trends."
    )
    
    st.divider()
    
    api_client = st.session_state.api_client
    
    # Visualization definitions
    visualizations = [
        {
            'filename': 'hr_trend.png',
            'title': 'Heart Rate Trend',
            'description': 'Multi-line plot showing heart rate over time for all patients'
        },
        {
            'filename': 'oxygen_distribution.png',
            'title': 'Oxygen Distribution',
            'description': 'Histogram with 92% threshold line showing oxygen level distribution'
        },
        {
            'filename': 'anomaly_counts.png',
            'title': 'Anomaly Counts',
            'description': 'Bar chart showing counts by anomaly type'
        }
    ]
    
    # Fetch and display visualizations
    with st.spinner("Loading visualizations..."):
        # Create columns for responsive layout
        cols = st.columns(1)
        
        for i, viz in enumerate(visualizations):
            try:
                image = fetch_visualization(api_client, viz['filename'])
                
                # Render-inspired visualization area
                st.markdown(f'<p class="tech-label">{viz["title"]}</p>', unsafe_allow_html=True)
                st.markdown('<div class="viz-card">', unsafe_allow_html=True)
                
                if image:
                    st.image(image, use_container_width=True)
                else:
                    st.markdown(f'<div style="padding: 40px; text-align: center; color: #6B7280; font-size: 14px;">{viz["title"]} not yet generated</div>', unsafe_allow_html=True)
                
                st.markdown('</div>', unsafe_allow_html=True)
                st.markdown("<br/>", unsafe_allow_html=True)
                
            except ConnectionError as e:
                st.error(f"Connection Error: {str(e)}")
                st.info("Please check if the backend API is running.")
                break
            
            except Exception as e:
                st.error(f"Error loading {viz['title']}: {str(e)}")
    
    # Info section
    st.divider()
    st.info(
        "**Tip:** Visualizations are generated by the pipeline. "
        "Run the pipeline from the 'Run Pipeline' page to generate fresh visualizations."
    )
